// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_project_ from "./routes/[project].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_printChapter from "./routes/api/printChapter.ts";
import * as $api_printChapterWithCover from "./routes/api/printChapterWithCover.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $index from "./routes/index.tsx";
import * as $new_project from "./routes/new-project.tsx";
import * as $AddProject from "./islands/AddProject.tsx";
import * as $AddSection from "./util/AddSection.tsx";
import * as $File from "./islands/File.tsx";
import * as $ProjectData from "./islands/ProjectData.tsx";
import * as $Projects from "./islands/Projects.tsx";
import * as $Sections from "./islands/Sections.tsx";
import * as $renderImages from "./islands/renderImages.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[project].tsx": $_project_,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/printChapter.ts": $api_printChapter,
    "./routes/api/printChapterWithCover.ts": $api_printChapterWithCover,
    "./routes/api/upload.ts": $api_upload,
    "./routes/index.tsx": $index,
    "./routes/new-project.tsx": $new_project,
  },
  islands: {
    "./islands/AddProject.tsx": $AddProject,
    "./islands/AddSection.tsx": $AddSection,
    "./islands/File.tsx": $File,
    "./islands/ProjectData.tsx": $ProjectData,
    "./islands/Projects.tsx": $Projects,
    "./islands/Sections.tsx": $Sections,
    "./islands/renderImages.tsx": $renderImages,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
