// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_chapter_ from "./routes/[chapter].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $add_chapter from "./routes/add-chapter.tsx";
import * as $api_printAllChapters from "./routes/api/printAllChapters.ts";
import * as $api_printChapter from "./routes/api/printChapter.ts";
import * as $api_printChapterWithCover from "./routes/api/printChapterWithCover.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $index from "./routes/index.tsx";
import * as $new_project from "./routes/new-project.tsx";
import * as $AddProject from "./islands/AddProject.tsx";
import * as $ChapterData from "./islands/ChapterData.tsx";
import * as $Chapters from "./islands/Chapters.tsx";
import * as $Chapters_Test from "./islands/Chapters_Test.tsx";
import * as $File from "./islands/File.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $HomeContent from "./islands/HomeContent.tsx";
import * as $LoaderIsland from "./islands/LoaderIsland.tsx";
import * as $Sections from "./islands/Sections.tsx";
import * as $generateChaptersFromJSON from "./islands/generateChaptersFromJSON.tsx";
import * as $generateIntroduction from "./islands/generateIntroduction.tsx";
import * as $printAllChapters from "./islands/printAllChapters.tsx";
import * as $renderImages from "./islands/renderImages.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[chapter].tsx": $_chapter_,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/add-chapter.tsx": $add_chapter,
    "./routes/api/printAllChapters.ts": $api_printAllChapters,
    "./routes/api/printChapter.ts": $api_printChapter,
    "./routes/api/printChapterWithCover.ts": $api_printChapterWithCover,
    "./routes/api/upload.ts": $api_upload,
    "./routes/index.tsx": $index,
    "./routes/new-project.tsx": $new_project,
  },
  islands: {
    "./islands/AddProject.tsx": $AddProject,
    "./islands/ChapterData.tsx": $ChapterData,
    "./islands/Chapters.tsx": $Chapters,
    "./islands/Chapters_Test.tsx": $Chapters_Test,
    "./islands/File.tsx": $File,
    "./islands/Hero.tsx": $Hero,
    "./islands/HomeContent.tsx": $HomeContent,
    "./islands/LoaderIsland.tsx": $LoaderIsland,
    "./islands/Sections.tsx": $Sections,
    "./islands/generateChaptersFromJSON.tsx": $generateChaptersFromJSON,
    "./islands/generateIntroduction.tsx": $generateIntroduction,
    "./islands/printAllChapters.tsx": $printAllChapters,
    "./islands/renderImages.tsx": $renderImages,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
